---
title: "Individual assignment 5"
author: "Sami Gibson"
date: "2026-04-27"
format: pdf
execute:
  message: false
  warning: false
---
# 1. Set up

## Packages
```{r}
#| label: packages
# reads in tidyverse package from library 
library(tidyverse)
# reads in here package from library 
library(here)
# reads in janitor package from library 
library(janitor)
# reads in readxl package from library 
library(readxl)
```

## Data
```{r}
#| label: data
#| 
# read in taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv")) 

# read in aquatic invertebrates data
aq_ins <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                    sheet = "Aquatic Insects") 

# read in site information
sites <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                   sheet = "sites")

# read in water quality information
water_quality <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                           sheet = "Water Quality",
                           na = c("", "n/a", "N/A", "over", "173+")) 
```
